### ISSUE TITLE
cursorline and vimdiff create black on dark grey text

### ISSUE THREAD

**Issue by fedemp** [romainl/Apprentice#9] opened 2015-06-17 13:48 UTC
Using `cursorline` when editing a merge conflict in vimdiff, added and modified text get a dark grey background with black text.
![screen shot 2015-06-17 at 10 45 46 am](https://cloud.githubusercontent.com/assets/735314/8208508/5d874eca-14de-11e5-8e5a-811a4aa93a45.png)

**Comment by romainl** [comment] 2015-06-17 14:54
Hi, could you give me more info on your environment? I can't reproduce that behavior here.
![vimdiff](https://cloud.githubusercontent.com/assets/344335/8210251/660557b2-1511-11e5-876d-9012f34411ab.png)

**Comment by fedemp** [comment] 2015-06-17 17:33
Using vim 7.4 in iterm with the colorscheme file from your repo. Not using tmux. My vimrc is at https://github.com/fedemp/dotvim but it doesn't seem to be related.

I started `vimdiff -u NONE foo bar`, then `:so colors/apprentice.vim` and finally `:set cursorline`.

**Comment by romainl** [comment] 2015-06-17 18:59
Hmm… I took my screenshot in Vim 7.4 in iTerm so we appear to have similar setups yet we have different results. Is that a basic diff (`vimdiff` or `:diffthis`) or a Fugitive-generated diff?

**Comment by fedemp** [comment] 2015-06-17 20:49
Both `vimdiff` and fugitive set as git mergetool show the same behaviour.

Using urxvt at home has the same issue too.

This is iterm preferences.

![screen shot 2015-06-17 at 5 47 32 pm](https://cloud.githubusercontent.com/assets/735314/8218411/17ae336a-1519-11e5-9a95-ee2922298ea5.png)

**Comment by romainl** [comment] 2016-09-04 12:21
Fixed as of commit 78af677e3db97d3c2a805a2018ece3a74b38c0aa.

**Closed by romainl** 2016-09-04 12:21 UTC
